name: Foothills Philharmonic Society
markdown: redcarpet
url: https://www.foothillsphilharmonic.com
permalink: /:categories/:year/:month/:day/:title
post_dirs: true
excerpt_separator: <!--more-->
include:
  - .well-known

defaults:
  -
    scope:
      path: ""
    values:
      description: "Bringing beautiful music to the Foothills in Southern Alberta, Canada"
      title_suffix: 'Foothills Philharmonic Society'
      image: "/images/default-fps-image.jpg"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
